<?php

$title = 'Products';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('product', ['action' => 'add']) ?>">Add new product</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>In Stock?</th>
    <th>Units in Stock</th>
    <th>Unit Purchase Price</th>
    <th>Unit Sale Price</th>
    <th>Supplier Name</th>
    <th>Actions</th>
</tr>
<?php foreach ($products as $product) : ?>
    <tr>
        <td><?= $this->escapeHtml($product->name) ?></td>
        <td><?= $this->escapeHtml($product->in_stock) ?></td>
        <td><?= $this->escapeHtml($product->units_in_stock) ?></td>
        <td><?= $this->escapeHtml($product->unit_purchase_price) ?></td>
        <td><?= $this->escapeHtml($product->unit_sale_price) ?></td>
        <td><?= $this->escapeHtml($product->sp_id) ?></td>
        <td>
            <a href="<?= $this->url('product', ['action' => 'edit', 'id' => $product->id]) ?>">Edit</a>
            <a href="<?= $this->url('product', ['action' => 'delete', 'id' => $product->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>