<?php

$title = 'Delete Product';
$url   = $this->url('product', ['action' => 'delete', 'id' => $p_id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete to
    "<?= $this->escapeHtml($product->p_name) ?>" ?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="p_id" value="<?= (int) $product->p_id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>