<?php

$title = 'Customers';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('customer', ['action' => 'add']) ?>" class="btn btn-success btn-lg btn-block">Add new customer</a>
</p>

<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Street</th>
            <th>City</th>
            <th>Country</th>
            <th>Postal Code</th>
            <th>Phone</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
<?php foreach ($customers as $customer) : ?>
    <tr>
        <td><?= $this->escapeHtml($customer->first_name) ?></td>
        <td><?= $this->escapeHtml($customer->last_name) ?></td>
        <td><?= $this->escapeHtml($customer->address_street) ?></td>
        <td><?= $this->escapeHtml($customer->address_city) ?></td>
        <td><?= $this->escapeHtml($customer->address_country) ?></td>
        <td><?= $this->escapeHtml($customer->address_post_code) ?></td>
        <td><?= $this->escapeHtml($customer->contact_phone_no) ?></td>
        <td>
            <a href="<?= $this->url('customer', ['action' => 'edit', 'id' => $customer->id]) ?>" class="btn btn-info btn-sm">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
                </svg>
            </a>
        </td>
        <td>
            <a href="<?= $this->url('customer', ['action' => 'delete', 'id' => $customer->id]) ?>" class="btn btn-danger btn-sm">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
                </svg>
            </a>
        </td>
    </tr>
<?php endforeach; ?>
</table>